// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDowM49p4gyK6NcFtDpk_ncImN_GOE7oXk',
    appId: '1:238883448538:web:67e8d075397d4df807a7e3',
    messagingSenderId: '238883448538',
    projectId: 'mycold-d6678',
    authDomain: 'mycold-d6678.firebaseapp.com',
    storageBucket: 'mycold-d6678.appspot.com',
    measurementId: 'G-M7DF55KFS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Q0WMHAEcEVusnji71TV2AaokKcwSyeI',
    appId: '1:238883448538:android:fce7ed476db8f86b07a7e3',
    messagingSenderId: '238883448538',
    projectId: 'mycold-d6678',
    storageBucket: 'mycold-d6678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARunlug55HRsPisQ5banALxxrC5C2hp9Y',
    appId: '1:238883448538:ios:421aac546becf6b307a7e3',
    messagingSenderId: '238883448538',
    projectId: 'mycold-d6678',
    storageBucket: 'mycold-d6678.appspot.com',
    iosClientId: '238883448538-1rkb3r75gevr7sn97o8139c8550tlnsp.apps.googleusercontent.com',
    iosBundleId: 'my.caspian.mycoldstaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARunlug55HRsPisQ5banALxxrC5C2hp9Y',
    appId: '1:238883448538:ios:421aac546becf6b307a7e3',
    messagingSenderId: '238883448538',
    projectId: 'mycold-d6678',
    storageBucket: 'mycold-d6678.appspot.com',
    iosClientId: '238883448538-1rkb3r75gevr7sn97o8139c8550tlnsp.apps.googleusercontent.com',
    iosBundleId: 'my.caspian.mycoldstaff',
  );
}
